<?php
/**
 * Helper Module for Rasamala Template - Theme Preset Definitions
 */
if (!defined('INDEX_AUTH') || INDEX_AUTH != 1) {
  die("can not access this file directly");
}

if (!function_exists('themePresetDefinitions')) {
  function themePresetDefinitions()
  {
    return [
      'simple_homepage' => [
        'label' => 'Simple - Search + Running Text',
        'description' => 'Preset paling sederhana: beranda fokus pencarian dengan running text bawah sebagai info singkat. Fitur lain tetap ringan.',
        'footer_home' => false,
        'settings' => [
          'classic_homepage_only_hero' => 1,
          'classic_topic_show' => 0,
          'classic_popular_collection' => 0,
          'classic_new_collection' => 0,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => '',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 0,
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_theme_color' => 'darkgray',
          'classic_font_family' => 'inter',
          'classic_hero_background_animation' => 'none',
          'classic_cursor_particles' => 'none',
        ],
      ],
      'all_show' => [
        'label' => 'Full - Topics + News + Collections + Top Reader + Map + Running Text',
        'description' => 'Preset paling lengkap: semua section utama, latest content, topic, koleksi populer/terbaru, top reader, map, ticker, footer, dan animasi.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 1,
          'classic_new_collection' => 1,
          'classic_top_reader' => 1,
          'classic_homepage_section_order' => 'topic;news;popular;new-collection;top-reader;map',
          'classic_map' => 'all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 'bottom',
          'classic_footer_show' => 1,
          'classic_hero_background_animation' => 'twinkle',
          'classic_cursor_particles' => 'auto',
        ],
      ],
      'simple_topics' => [
        'label' => 'Topic-Focused Directory',
        'description' => 'Direktori pencarian yang berfokus pada kategori dan ikon subjek pustaka. Koleksi buku dan peta disembunyikan.',
        'footer_home' => false,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 0,
          'classic_new_collection' => 0,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => 'topic',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 0,
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_theme_color' => 'warmgray',
          'classic_font_family' => 'inter',
          'classic_hero_background_animation' => 'bubbles',
        ],
      ],
      'simple_topics_footer' => [
        'label' => 'Classic Directory with Footer',
        'description' => 'Tampilan direktori subjek kategori klasik lengkap dengan tautan footer informasi perpustakaan.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 0,
          'classic_new_collection' => 0,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => 'topic',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 0,
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_theme_color' => 'warmlibrary',
          'classic_font_family' => 'poppins',
          'classic_hero_background_animation' => 'bubbles',
        ],
      ],
      'fun' => [
        'label' => 'Modern Interactive Portal',
        'description' => 'Portal dinamis interaktif dengan ornamen modern, korsel koleksi aktif, font tebal, dan partikel cursor melayang.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 1,
          'classic_new_collection' => 1,
          'classic_top_reader' => 1,
          'classic_homepage_section_order' => 'topic;news;popular;new-collection;top-reader',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_theme_color' => 'warmlibrary',
          'classic_font_family' => 'poppins',
          'classic_hero_background_animation' => 'glow',
          'classic_cursor_particles' => 'medium',
        ],
      ],
      'office' => [
        'label' => 'Simple + Topics',
        'description' => 'Preset ringkas: search utama ditambah daftar topic saja. Teks section Topics disembunyikan agar tampil seperti direktori sederhana.',
        'footer_home' => false,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_topic_heading_display' => 'hide',
          'classic_popular_collection' => 0,
          'classic_new_collection' => 0,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => 'topic',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_theme_color' => 'contemporarytechlibrary',
          'classic_font_family' => 'inter',
          'classic_hero_background_animation' => 'waves',
          'classic_cursor_particles' => 'none',
        ],
      ],
      'academic' => [
        'label' => 'Academic & Research Portal',
        'description' => 'Desain portal prestisius untuk sekolah tinggi/universitas. Menonjolkan daftar bacaan, peringkat pembaca terbaik, dan peta kampus.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 0,
          'classic_new_collection' => 1,
          'classic_top_reader' => 1,
          'classic_homepage_section_order' => 'topic;news;new-collection;top-reader;map',
          'classic_map' => 'all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_hero_background_animation' => 'twinkle',
        ],
      ],
      'minimalist' => [
        'label' => 'Minimalist Modern Portal',
        'description' => 'Tema ultra-bersih dengan transisi warna halus, font sans-serif tipis, dan efek orbs melayang yang estetik.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 0,
          'classic_popular_collection' => 0,
          'classic_new_collection' => 0,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => '',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_hero_background_animation' => 'twinkle',
          'classic_cursor_particles' => 'low',
        ],
      ],
      'minimal_white' => [
        'label' => 'Minimal White Portal',
        'description' => 'Portal putih minimalis dengan kontras teks tegas, surface bersih, dan aksen biru kecil agar tampilan sangat ringan.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 0,
          'classic_new_collection' => 1,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => 'topic;news;new-collection',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 0,
          'classic_footer_show' => 1,
          'classic_theme_color' => 'minimalwhite',
          'classic_font_family' => 'inter',
          'classic_hero_background_animation' => 'none',
          'classic_cursor_particles' => 'none',
        ],
      ],
      'dark_gray' => [
        'label' => 'Dark Gray Portal',
        'description' => 'Portal dark gray netral yang tidak kebiruan, cocok untuk tampilan modern dan nyaman dibaca pada layar gelap.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 1,
          'classic_new_collection' => 1,
          'classic_top_reader' => 0,
          'classic_homepage_section_order' => 'topic;news;popular;new-collection',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 'bottom',
          'classic_footer_show' => 1,
          'classic_theme_color' => 'darkgray',
          'classic_font_family' => 'inter',
          'classic_hero_background_animation' => 'twinkle',
          'classic_background_animation_speed' => 'slow',
          'classic_cursor_particles' => 'low',
        ],
      ],
      'futuristic' => [
        'label' => 'Futuristic Digital Portal',
        'description' => 'Desain gelap sci-fi dengan partikel laser neon, animasi hujan kode siber, dan interaksi pointer modern.',
        'footer_home' => true,
        'settings' => [
          'classic_homepage_only_hero' => 0,
          'classic_topic_show' => 1,
          'classic_popular_collection' => 1,
          'classic_new_collection' => 1,
          'classic_top_reader' => 1,
          'classic_homepage_section_order' => 'topic;news;popular;new-collection;top-reader',
          'classic_map' => 'hide_all',
          'classic_home_display_show' => 'below',
          'classic_ticker_show' => 'bottom',
          'classic_footer_show' => 1,
          'classic_theme_color' => 'darkgray',
          'classic_font_family' => 'poppins',
          'classic_cursor_custom_icon' => 'electric-bolt',
        ],
      ],
      'custom' => [
        'label' => 'Custom (Fully Unlocked)',
        'description' => 'Membuka penuh seluruh konfigurasi tema secara mendalam. Nilai khusus setiap kolom input akan digunakan langsung.',
        'footer_home' => null,
        'settings' => [],
      ],
    ];
  }
}
